title: Sentry Cookie Scanner
scanner:
  headless: true
  numPages: 0
  captureHar: false
  saveScreenshots: false
  emulateDevice:
    viewport:
      height: 1920
      width: 1080
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.3"
output:
  outDir: scan_results # directory to save the raw scan results
  reportDir: scan_reports # directory to save the aggregated scan reports
target_list: ./target.yaml # path to the target list file
maxConcurrent: 20 # number of concurrent scans